  services:

    db:
      image: postgres:16
      container_name: student-db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: students
      ports:
        - "5432:5432"

    api:
      build: .
      container_name: student-api
      depends_on:
        - db
      ports:
        - "5000:5000"
      environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/students