name: Python CI/CD

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:

  lint:
    runs-on: [self-hosted, aws]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install flake8
      - run: flake8 .

  test:
    runs-on: [self-hosted, aws]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest
  
  build:
    needs: [lint, test]
    runs-on: [self-hosted, aws]
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t pythonapp:${{ github.sha }} .

  scan:
    needs: build
    runs-on: [self-hosted, aws]
    steps:
      - name: Scan Docker Image
        run: |
          trivy image --exit-code 1 --severity CRITICAL pythonapp:${{ github.sha }}

  deploy:
    needs: [build, scan ]
    runs-on: [self-hosted, aws]
    steps:
      - run: |
          docker rm -f pythonapp || true
          docker run -d \
            --name pythonapp \
            -p 5000:5000 \
            pythonapp:${{ github.sha }}

      - run: |
          for i in {1..15}; do
             curl -f http://localhost:5000/api/v1/healthcheck && exit 0
             sleep 2
          done
          echo "Health check failed"
          exit 1
